-- Initial database schema for Alpha Vault
-- This migration creates all the necessary tables for the financial management system

-- Users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    account_type VARCHAR(255) NOT NULL CHECK (account_type IN ('BASIC', 'PREMIUM', 'ADMIN')),
    is_active BOOLEAN NOT NULL DEFAULT true,
    is_verified BOOLEAN NOT NULL DEFAULT false,
    two_factor_enabled BOOLEAN NOT NULL DEFAULT false,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    account_locked_until TIMESTAMP,
    email_verified_at TIMESTAMP,
    last_login_at TIMESTAMP,
    password_reset_token VARCHAR(255),
    password_reset_token_expiry TIMESTAMP,
    terms_accepted_at TIMESTAMP,
    preferred_currency VARCHAR(255),
    preferred_language VARCHAR(255),
    profile_image_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Budgets table
CREATE TABLE IF NOT EXISTS budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    total_budget NUMERIC(19,4) NOT NULL,
    total_spent NUMERIC(19,4) NOT NULL DEFAULT 0,
    currency VARCHAR(3),
    rollover_enabled BOOLEAN NOT NULL DEFAULT false,
    carry_over_amount NUMERIC(19,4),
    alert_threshold_percent INTEGER NOT NULL DEFAULT 80,
    notes VARCHAR(500),
    deleted_by VARCHAR(100),
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT uk_budget_user_year_month UNIQUE (user_id, year, month),
    CONSTRAINT fk_budget_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Budget Categories table
CREATE TABLE IF NOT EXISTS budget_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL CHECK (category IN (
        'RENT', 'MORTGAGE', 'UTILITIES', 'INTERNET_PHONE', 'HOME_INSURANCE', 'PROPERTY_TAX',
        'HOME_MAINTENANCE', 'GROCERIES', 'RESTAURANTS', 'COFFEE_SNACKS', 'FOOD_DELIVERY',
        'FUEL', 'CAR_PAYMENT', 'CAR_INSURANCE', 'CAR_REPAIRS', 'PARKING_TOLLS', 'PUBLIC_TRANSPORT',
        'HEALTH_INSURANCE', 'MEDICAL', 'PHARMACY', 'FITNESS', 'PERSONAL_CARE', 'CLOTHING',
        'ELECTRONICS', 'HOME_SUPPLIES', 'BEAUTY_COSMETICS', 'CHILDCARE', 'EDUCATION_CHILD',
        'TOYS_GAMES', 'PET_EXPENSES', 'TUITION', 'ONLINE_COURSES', 'BOOKS', 'WORKSHOPS',
        'STREAMING', 'MOVIES_EVENTS', 'TRAVEL', 'HOBBIES', 'LOAN_PAYMENT', 'CREDIT_CARD_PAYMENT',
        'SAVINGS_CONTRIBUTION', 'INVESTMENT_CONTRIBUTION', 'WORK_TOOLS', 'PROFESSIONAL_SERVICES',
        'PROFESSIONAL_SUBSCRIPTIONS', 'OFFICE_RENT', 'CHARITY', 'GIFTS', 'RELIGIOUS_OFFERING',
        'EMERGENCY_EXPENSE', 'ACCIDENT', 'UNPLANNED_TRAVEL', 'MEDICAL_EMERGENCY', 'BANK_FEES',
        'LATE_FEES', 'SERVICE_CHARGES', 'FOREIGN_FEES'
    )),
    allocated NUMERIC(19,4) NOT NULL,
    spent_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT uk_budgetcat_budget_category UNIQUE (budget_id, category),
    CONSTRAINT fk_budgetcat_budget FOREIGN KEY (budget_id) REFERENCES budgets(id)
);

-- Expenses table
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount NUMERIC(19,4) NOT NULL,
    currency VARCHAR(3),
    expense_date DATE NOT NULL,
    category VARCHAR(50) NOT NULL CHECK (category IN (
        'RENT', 'MORTGAGE', 'UTILITIES', 'INTERNET_PHONE', 'HOME_INSURANCE', 'PROPERTY_TAX',
        'HOME_MAINTENANCE', 'GROCERIES', 'RESTAURANTS', 'COFFEE_SNACKS', 'FOOD_DELIVERY',
        'FUEL', 'CAR_PAYMENT', 'CAR_INSURANCE', 'CAR_REPAIRS', 'PARKING_TOLLS', 'PUBLIC_TRANSPORT',
        'HEALTH_INSURANCE', 'MEDICAL', 'PHARMACY', 'FITNESS', 'PERSONAL_CARE', 'CLOTHING',
        'ELECTRONICS', 'HOME_SUPPLIES', 'BEAUTY_COSMETICS', 'CHILDCARE', 'EDUCATION_CHILD',
        'TOYS_GAMES', 'PET_EXPENSES', 'TUITION', 'ONLINE_COURSES', 'BOOKS', 'WORKSHOPS',
        'STREAMING', 'MOVIES_EVENTS', 'TRAVEL', 'HOBBIES', 'LOAN_PAYMENT', 'CREDIT_CARD_PAYMENT',
        'SAVINGS_CONTRIBUTION', 'INVESTMENT_CONTRIBUTION', 'WORK_TOOLS', 'PROFESSIONAL_SERVICES',
        'PROFESSIONAL_SUBSCRIPTIONS', 'OFFICE_RENT', 'CHARITY', 'GIFTS', 'RELIGIOUS_OFFERING',
        'EMERGENCY_EXPENSE', 'ACCIDENT', 'UNPLANNED_TRAVEL', 'MEDICAL_EMERGENCY', 'BANK_FEES',
        'LATE_FEES', 'SERVICE_CHARGES', 'FOREIGN_FEES'
    )),
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('CASH', 'CARD', 'CHECK', 'TRANSFER', 'CRYPTO', 'PAYPAL')),
    description VARCHAR(500),
    deleted_by VARCHAR(100),
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_expense_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Incomes table
CREATE TABLE IF NOT EXISTS incomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    amount NUMERIC(19,4) NOT NULL,
    currency VARCHAR(3),
    income_date DATE NOT NULL,
    source VARCHAR(255) NOT NULL,
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('CASH', 'CARD', 'CHECK', 'TRANSFER', 'CRYPTO', 'PAYPAL')),
    received BOOLEAN NOT NULL DEFAULT false,
    description VARCHAR(500),
    deleted_by VARCHAR(100),
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_income_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Debts table
CREATE TABLE IF NOT EXISTS debts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    creditor_name VARCHAR(160) NOT NULL,
    principal_amount NUMERIC(19,4) NOT NULL,
    remaining_amount NUMERIC(19,4) NOT NULL,
    interest_rate_apr NUMERIC(7,4) NOT NULL,
    min_payment NUMERIC(19,4) NOT NULL,
    due_date DATE NOT NULL,
    billing_cycle VARCHAR(10) NOT NULL CHECK (billing_cycle IN ('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')),
    status VARCHAR(16) NOT NULL CHECK (status IN ('ACTIVE', 'DELINQUENT', 'PAID_OFF', 'CLOSED', 'CANCELLED')),
    currency VARCHAR(3),
    account_ref VARCHAR(64),
    notes VARCHAR(1000),
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_debt_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Debt History table
CREATE TABLE IF NOT EXISTS debt_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id BIGINT NOT NULL,
    payment_amount NUMERIC(19,4) NOT NULL,
    payment_date DATE NOT NULL,
    remaining_after_payment NUMERIC(19,4) NOT NULL,
    payment_method VARCHAR(16) NOT NULL CHECK (payment_method IN ('CASH', 'CARD', 'CHECK', 'TRANSFER', 'CRYPTO', 'PAYPAL')),
    note VARCHAR(500),
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_debthistory_debt FOREIGN KEY (debt_id) REFERENCES debts(id)
);

-- Investments table
CREATE TABLE IF NOT EXISTS investments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    investment_type VARCHAR(32) NOT NULL CHECK (investment_type IN ('STOCKS', 'BONDS', 'MUTUAL_FUNDS', 'ETF', 'REAL_ESTATE', 'BUSINESS', 'COMMODITIES', 'FOREX', 'CRYPTO', 'OTHER')),
    symbol VARCHAR(32),
    platform VARCHAR(120),
    amount_invested NUMERIC(19,4) NOT NULL,
    current_value NUMERIC(19,4),
    current_price NUMERIC(19,8),
    quantity NUMERIC(24,8),
    fees NUMERIC(19,4),
    start_date DATE NOT NULL,
    sold_date DATE,
    sold_value NUMERIC(19,4),
    risk_level VARCHAR(16) CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
    status VARCHAR(16) NOT NULL CHECK (status IN ('OPEN', 'CLOSED')),
    currency VARCHAR(3),
    notes TEXT,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT fk_investment_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Saving Goals table
CREATE TABLE IF NOT EXISTS saving_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    target_amount NUMERIC(19,4) NOT NULL,
    current_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    deadline DATE NOT NULL,
    category VARCHAR(40) NOT NULL CHECK (category IN ('HEALTH', 'MARRIAGE', 'EDUCATION', 'TRAVEL', 'EMERGENCY', 'OTHER')),
    priority VARCHAR(10) NOT NULL CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW')),
    status VARCHAR(15) NOT NULL CHECK (status IN ('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED')),
    currency VARCHAR(3),
    notes VARCHAR(500),
    achieved_at TIMESTAMP,
    version BIGINT DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP,
    CONSTRAINT uk_goal_user_name UNIQUE (user_id, name),
    CONSTRAINT fk_goal_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_budget_user ON budgets(user_id);
CREATE INDEX IF NOT EXISTS idx_budget_year_month ON budgets(year, month);
CREATE INDEX IF NOT EXISTS idx_budget_deleted ON budgets(deleted_at);

CREATE INDEX IF NOT EXISTS idx_budgetcat_budget ON budget_categories(budget_id);
CREATE INDEX IF NOT EXISTS idx_budgetcat_category ON budget_categories(category);
CREATE INDEX IF NOT EXISTS idx_budgetcat_deleted ON budget_categories(deleted_at);

CREATE INDEX IF NOT EXISTS idx_expense_user ON expenses(user_id);
CREATE INDEX IF NOT EXISTS idx_expense_date ON expenses(expense_date);
CREATE INDEX IF NOT EXISTS idx_expense_category ON expenses(category);
CREATE INDEX IF NOT EXISTS idx_expense_payment_method ON expenses(payment_method);
CREATE INDEX IF NOT EXISTS idx_expense_deleted ON expenses(deleted_at);

CREATE INDEX IF NOT EXISTS idx_income_user ON incomes(user_id);
CREATE INDEX IF NOT EXISTS idx_income_date ON incomes(income_date);
CREATE INDEX IF NOT EXISTS idx_income_payment_method ON incomes(payment_method);
CREATE INDEX IF NOT EXISTS idx_income_deleted ON incomes(deleted_at);

CREATE INDEX IF NOT EXISTS idx_debt_user ON debts(user_id);
CREATE INDEX IF NOT EXISTS idx_debt_status ON debts(status);
CREATE INDEX IF NOT EXISTS idx_debt_due_date ON debts(due_date);
CREATE INDEX IF NOT EXISTS idx_debt_deleted ON debts(deleted_at);

CREATE INDEX IF NOT EXISTS idx_debt_history_debt ON debt_history(debt_id);
CREATE INDEX IF NOT EXISTS idx_debt_history_date ON debt_history(payment_date);

CREATE INDEX IF NOT EXISTS idx_inv_user ON investments(user_id);
CREATE INDEX IF NOT EXISTS idx_inv_type ON investments(investment_type);
CREATE INDEX IF NOT EXISTS idx_inv_symbol ON investments(symbol);
CREATE INDEX IF NOT EXISTS idx_inv_status ON investments(status);
CREATE INDEX IF NOT EXISTS idx_inv_deleted ON investments(deleted_at);

CREATE INDEX IF NOT EXISTS idx_goal_user ON saving_goals(user_id);
CREATE INDEX IF NOT EXISTS idx_goal_deadline ON saving_goals(deadline);
CREATE INDEX IF NOT EXISTS idx_goal_status ON saving_goals(status);
CREATE INDEX IF NOT EXISTS idx_goal_deleted ON saving_goals(deleted_at);
