/*
  Alpha Vault Financial System
  
  @author Mohamed Dhaoui
  @enum ExpenseCategoryIcons
  @description Icon mappings for expense categories using Material Design icons
  Supports both enum values and human-readable labels
*/

export const ExpenseCategoryIcons: Record<string, string> = {
  // FIXED LIVING EXPENSES - Enum Values
  'RENT': 'home',
  'MORTGAGE': 'account_balance',
  'UTILITIES': 'electrical_services',
  'INTERNET_PHONE': 'wifi',
  'HOME_INSURANCE': 'security',
  'PROPERTY_TAX': 'receipt_long',
  'HOME_MAINTENANCE': 'build',

  // FOOD & DINING - Enum Values
  'GROCERIES': 'shopping_cart',
  'RESTAURANTS': 'restaurant',
  'COFFEE_SNACKS': 'local_cafe',
  'FOOD_DELIVERY': 'delivery_dining',

  // TRANSPORTATION - Enum Values
  'FUEL': 'local_gas_station',
  'CAR_PAYMENT': 'directions_car',
  'CAR_INSURANCE': 'car_rental',
  'CAR_REPAIRS': 'build_circle',
  'PARKING_TOLLS': 'local_parking',
  'PUBLIC_TRANSPORT': 'directions_bus',

  // PERSONAL & HEALTH - Enum Values
  'HEALTH_INSURANCE': 'health_and_safety',
  'MEDICAL': 'medical_services',
  'PHARMACY': 'local_pharmacy',
  'FITNESS': 'fitness_center',
  'PERSONAL_CARE': 'face',

  // SHOPPING & ESSENTIALS - Enum Values
  'CLOTHING': 'checkroom',
  'ELECTRONICS': 'devices',
  'HOME_SUPPLIES': 'home_repair_service',
  'BEAUTY_COSMETICS': 'face_retouching_natural',

  // FAMILY & CHILDCARE - Enum Values
  'CHILDCARE': 'child_care',
  'EDUCATION_CHILD': 'school',
  'TOYS_GAMES': 'toys',
  'PET_EXPENSES': 'pets',

  // EDUCATION & SELF-DEVELOPMENT - Enum Values
  'TUITION': 'school',
  'ONLINE_COURSES': 'computer',
  'BOOKS': 'menu_book',
  'WORKSHOPS': 'workspace_premium',

  // ENTERTAINMENT & LEISURE - Enum Values
  'STREAMING': 'stream',
  'MOVIES_EVENTS': 'movie',
  'TRAVEL': 'flight',
  'HOBBIES': 'sports_esports',

  // DEBT & SAVINGS - Enum Values
  'LOAN_PAYMENT': 'account_balance_wallet',
  'CREDIT_CARD_PAYMENT': 'credit_card',
  'SAVINGS_CONTRIBUTION': 'savings',
  'INVESTMENT_CONTRIBUTION': 'trending_up',

  // BUSINESS & PROFESSIONAL - Enum Values
  'WORK_TOOLS': 'handyman',
  'PROFESSIONAL_SERVICES': 'business',
  'PROFESSIONAL_SUBSCRIPTIONS': 'subscriptions',
  'OFFICE_RENT': 'business_center',

  // GIVING & DONATIONS - Enum Values
  'CHARITY': 'volunteer_activism',
  'GIFTS': 'card_giftcard',
  'RELIGIOUS_OFFERING': 'church',

  // EMERGENCY & UNPLANNED - Enum Values
  'EMERGENCY_EXPENSE': 'emergency',
  'ACCIDENT': 'warning',
  'UNPLANNED_TRAVEL': 'flight_takeoff',
  'MEDICAL_EMERGENCY': 'emergency_medical_services',

  // FEES & CHARGES - Enum Values
  'BANK_FEES': 'account_balance',
  'LATE_FEES': 'schedule',
  'SERVICE_CHARGES': 'receipt',
  'FOREIGN_FEES': 'currency_exchange',

  // COMMON LABELS (Human-readable names)
  'Housing': 'home',
  'Food': 'restaurant',
  'Transport': 'directions_car',
  'Transportation': 'directions_car',
  'Healthcare': 'medical_services',
  'Health': 'medical_services',
  'Shopping': 'shopping_cart',
  'Entertainment': 'movie',
  'Business': 'business',
  'Travel': 'flight',
  'Utilities': 'electrical_services',
  'Insurance': 'security',
  'Taxes': 'receipt_long',
  'Fuel': 'local_gas_station',
  'Parking': 'local_parking',
  'Public Transport': 'directions_bus',
  'Bus': 'directions_bus',
  'Train': 'train',
  'Subway': 'subway',
  'Taxi': 'local_taxi',
  'Uber': 'local_taxi',
  'Lyft': 'local_taxi',
  'Medical': 'medical_services',
  'Doctor': 'medical_services',
  'Hospital': 'local_hospital',
  'Pharmacy': 'local_pharmacy',
  'Medicine': 'local_pharmacy',
  'Drugs': 'local_pharmacy',
  'Fitness': 'fitness_center',
  'Gym': 'fitness_center',
  'Exercise': 'fitness_center',
  'Sports': 'sports',
  'Personal Care': 'face',
  'Beauty': 'face_retouching_natural',
  'Cosmetics': 'face_retouching_natural',
  'Clothing': 'checkroom',
  'Clothes': 'checkroom',
  'Fashion': 'checkroom',
  'Electronics': 'devices',
  'Gadgets': 'devices',
  'Technology': 'devices',
  'Home Supplies': 'home_repair_service',
  'Supplies': 'home_repair_service',
  'Household': 'home_repair_service',
  'Childcare': 'child_care',
  'Children': 'child_care',
  'Kids': 'child_care',
  'School': 'school',
  'Learning': 'school',
  'Books': 'menu_book',
  'Reading': 'menu_book',
  'Library': 'menu_book',
  'Movies': 'movie',
  'Cinema': 'movie',
  'Theater': 'theater_comedy',
  'Streaming': 'stream',
  'Netflix': 'stream',
  'Hulu': 'stream',
  'Disney': 'stream',
  'Amazon Prime': 'stream',
  'Hobbies': 'sports_esports',
  'Games': 'sports_esports',
  'Gaming': 'sports_esports',
  'Music': 'music_note',
  'Concerts': 'music_note',
  'Events': 'event',
  'Parties': 'celebration',
  'Celebrations': 'celebration',
  'Gifts': 'card_giftcard',
  'Present': 'card_giftcard',
  'Presents': 'card_giftcard',
  'Charity': 'volunteer_activism',
  'Donations': 'volunteer_activism',
  'Donation': 'volunteer_activism',
  'Emergency': 'emergency',
  'Urgent': 'emergency',
  'Accident': 'warning',
  'Repairs': 'build_circle',
  'Fix': 'build_circle',
  'Service': 'handyman',
  'Services': 'handyman',
  'Professional': 'business',
  'Work': 'business',
  'Office': 'business_center',
  'Bank': 'account_balance',
  'Banking': 'account_balance',
  'ATM': 'atm',
  'Cash': 'money',
  'Credit Card': 'credit_card',
  'Debit Card': 'credit_card',
  'Card': 'credit_card',
  'Check': 'receipt',
  'Cheque': 'receipt',
  'Transfer': 'swap_horiz',
  'Wire Transfer': 'swap_horiz',
  'Online Payment': 'payment',
  'PayPal': 'payment',
  'Venmo': 'payment',
  'Zelle': 'payment',
  'Cryptocurrency': 'currency_bitcoin',
  'Bitcoin': 'currency_bitcoin',
  'Crypto': 'currency_bitcoin',
  'Investment': 'trending_up',
  'Stocks': 'trending_up',
  'Savings': 'savings',
  'Retirement': 'account_balance_wallet',
  'Pension': 'account_balance_wallet',
  'Loan': 'account_balance_wallet',
  'Debt': 'account_balance_wallet',
  'Mortgage': 'account_balance',
  'Rent': 'home',
  'Lease': 'home',
  'Property': 'home',
  'Real Estate': 'home',
  'Internet': 'wifi',
  'Phone': 'phone',
  'Mobile': 'phone',
  'Cellular': 'phone',
  'Electricity': 'electrical_services',
  'Electric': 'electrical_services',
  'Power': 'electrical_services',
  'Water': 'water_drop',
  'Heating': 'thermostat',
  'Cooling': 'ac_unit',
  'Air Conditioning': 'ac_unit',
  'AC': 'ac_unit',
  'Grocery': 'shopping_cart',
  'Groceries': 'shopping_cart',
  'Supermarket': 'shopping_cart',
  'Market': 'shopping_cart',
  'Restaurant': 'restaurant',
  'Dining': 'restaurant',
  'Dining Out': 'restaurant',
  'Eat Out': 'restaurant',
  'Fast Food': 'restaurant',
  'Coffee': 'local_cafe',
  'Cafe': 'local_cafe',
  'Starbucks': 'local_cafe',
  'Snacks': 'local_cafe',
  'Delivery': 'delivery_dining',
  'Takeout': 'delivery_dining',
  'Uber Eats': 'delivery_dining',
  'DoorDash': 'delivery_dining',
  'Grubhub': 'delivery_dining',

  // LOWERCASE ENUM VALUES (from actual data)
  'groceries': 'shopping_cart',
  'utilities': 'electrical_services',
  'rent': 'home',
  'travel': 'flight',
  'food_delivery': 'delivery_dining',
  'public_transport': 'directions_bus',
  'credit_card_payment': 'credit_card',
  'home_supplies': 'home_repair_service',
  'coffee_snacks': 'local_cafe',
  'professional_services': 'business',
  'mortgage': 'account_balance',
  'internet_phone': 'wifi',
  'home_insurance': 'security',
  'property_tax': 'receipt_long',
  'home_maintenance': 'build',
  'restaurants': 'restaurant',
  'fuel': 'local_gas_station',
  'car_payment': 'directions_car',
  'car_insurance': 'car_rental',
  'car_repairs': 'build_circle',
  'parking_tolls': 'local_parking',
  'health_insurance': 'health_and_safety',
  'medical': 'medical_services',
  'pharmacy': 'local_pharmacy',
  'fitness': 'fitness_center',
  'personal_care': 'face',
  'clothing': 'checkroom',
  'electronics': 'devices',
  'beauty_cosmetics': 'face_retouching_natural',
  'childcare': 'child_care',
  'education_child': 'school',
  'toys_games': 'toys',
  'pet_expenses': 'pets',
  'tuition': 'school',
  'online_courses': 'computer',
  'books': 'menu_book',
  'workshops': 'workspace_premium',
  'streaming': 'stream',
  'movies_events': 'movie',
  'hobbies': 'sports_esports',
  'loan_payment': 'account_balance_wallet',
  'savings_contribution': 'savings',
  'investment_contribution': 'trending_up',
  'work_tools': 'handyman',
  'professional_subscriptions': 'subscriptions',
  'office_rent': 'business_center',
  'charity': 'volunteer_activism',
  'gifts': 'card_giftcard',
  'religious_offering': 'church',
  'emergency_expense': 'emergency',
  'accident': 'warning',
  'unplanned_travel': 'flight_takeoff',
  'medical_emergency': 'emergency_medical_services',
  'bank_fees': 'account_balance',
  'late_fees': 'schedule',
  'service_charges': 'receipt',
  'foreign_fees': 'currency_exchange'
};
